"""The FZD API's response and request shapes, as `TypedDict`s.

GENERATED by `uv run scripts/api_types.py`; do not edit.
Source: fzd-api f612425 (with uncommitted changes), API version 0.1.0.
Each class is one schema of the API's OpenAPI document under its own name
and wire field names, with the schema's field descriptions as attribute
docstrings. Instants are ISO 8601 strings. A `TypedDict` is a claim the type
checker verifies at every read site, not a parser: nothing validates a
response against it.
"""

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


class CatalogueTrackResponse(TypedDict):
    track_id: int
    """
    A `tracks` id, the value a vote on a slot names.
    """
    name: str
    """
    The track's name, as a client prints it: `mirror Sand Ocean` for a mirror track. A standard track and its classic twin share a name; `type` tells them apart.
    """
    type: str
    """
    `standard`, `mirror`, `classic` or `glitch`.
    """
    short_name: str | None
    """
    The track's short name, or null where none is stored.
    """


class DatabaseHealthResponse(TypedDict):
    status: str
    database: str
    """
    The schema the server reports, from `SELECT DATABASE()`.
    """
    configured: str
    """
    The schema this process asked for. Differs from `database` only when something is wrong.
    """
    matches: bool
    """
    Whether the two agree. The one field worth alerting on.
    """


class EventGroupResponse(TypedDict):
    group_id: int
    """
    A `divisions` or `teams` id, as `group_kind` says; the handle a scoreboard filter names.
    """
    name: str
    alt_name: str | None
    """
    A second name for the group, or null.
    """
    emote: str | None
    """
    The group's emote as an opaque string, or null. Not rendered here.
    """
    display_order: int
    """
    Where the group sits when groups are listed; lower first.
    """


class EventHostResponse(TypedDict):
    scheduled_event_id: int
    event: str
    """
    The recurring event this is an instance of, e.g. `friday_eu`.
    """
    host_tag: str | None
    """
    The host's in-game name, or null if the event has no host or the host has never set one.
    """


class EventResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id, the same one `/v1/events/{id}/host` takes.
    """
    event: str
    """
    The recurring event this is an instance of, e.g. `friday_eu`.
    """
    display_name: str | None
    """
    What this instance calls itself, or null — most instances have none and `event` is the fallback.
    """
    starts_at: str
    """
    When the event opens, as a UTC instant.
    """
    ends_at: str
    """
    When the event closes, as a UTC instant. Exclusive: an event is no longer active at this instant.
    """
    mode: str
    """
    `99` or `classic`.
    """
    scoring_method: str
    """
    `points`, `placement` or `time`.
    """
    machine_input_required: bool
    """
    Whether a score submission for this event must name a machine.
    """


class EventScoringRequest(TypedDict):
    scoring_method: Literal["points", "time"]
    """
    How a result on this event is read: a score that adds up, or a time that loses to the leader. Matched without regard to case.
    """
    num_mulligans: NotRequired[int]
    """
    How many of a player's results drop before totalling. May exceed the number of slots.
    """
    max_time_loss_cs: NotRequired[int | None]
    """
    The most a time result can lose to the slot's leader, in centiseconds. Required under `time`, must be null under `points`.
    """


class EventScoringResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id.
    """
    scoring_method: str
    """
    `points` or `time`.
    """
    num_mulligans: int
    """
    How many of a player's results drop before totalling.
    """
    max_time_loss_cs: int | None
    """
    The most a time result can lose to the slot's leader, in centiseconds, or null for no cap.
    """


class EventTypeResponse(TypedDict):
    event_type_id: int
    """
    An `events` id, what `/v1/events/latest?event_type=` takes.
    """
    name: str
    """
    The definition's name, unique.
    """
    description: str | None
    mode: str | None
    """
    `99` or `classic`, or null.
    """
    scoring_method: str
    """
    `points`, `placement` or `time`.
    """
    recurring: bool
    """
    Whether this is a weekly rather than a one-off.
    """


class Ggp8CapacityResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id.
    """
    event: str
    """
    The recurring event this is an instance of.
    """
    display_name: str | None
    """
    What this instance calls itself, or null.
    """
    kind: str
    """
    `division` or `team`. Which one an event uses is a property of the event.
    """
    name: str
    """
    The division's or team's name.
    """
    alt_name: str | None
    """
    Its short label, or null. Most GGP8 groups have none.
    """
    capacity: int | None
    """
    How many places the group has, or null if it is uncapped. Null means unlimited, not full.
    """
    registered: int
    """
    How many players currently hold a place in it.
    """


class Ggp8EvaluationAnswerResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id.
    """
    self_evaluation: str | None
    """
    The stored "F-Zero 99 experience" answer.
    """
    most_recent_event: str | None
    """
    The stored "most recent major event" answer.
    """
    answered_for_this_event: bool
    """
    Always true after a write.
    """


class Ggp8EvaluationRequest(TypedDict):
    discord_user_name: NotRequired[str | None]
    tag: NotRequired[str | None]
    self_evaluation_id: int
    """
    A `stats_self_eval` id.
    """
    most_recent_event_id: int
    """
    A `stats_recent_99` id.
    """


class Ggp8PlayerEvaluationResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id.
    """
    event: str
    """
    The recurring event this is an instance of.
    """
    display_name: str | None
    """
    What this instance calls itself, or null.
    """
    tag: str | None
    """
    The player's in-game name, or null. Not unique.
    """
    discord_user_name: str | None
    """
    The player's Discord username as stored. Mutable, and never the key.
    """
    discord_user_id: str | None
    """
    The player's Discord account id, as a string, or null. A string because a snowflake exceeds 2^53.
    """
    self_evaluation: str | None
    """
    Their answer to "What is your F-Zero 99 experience?", or null if they did not answer.
    """
    most_recent_event: str | None
    """
    Their answer to "What was your most recent major F-ZERO 99 event that you played in?", or null.
    """


class Ggp8RegistrationResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id, the same one `/v1/events/{id}/host` takes.
    """
    event: str
    """
    The recurring event this is an instance of.
    """
    display_name: str | None
    """
    What this instance calls itself, or null. GGP8's five instances all have one.
    """
    tag: str | None
    """
    The player's in-game name, or null if they have never set one. Ten characters, F-Zero 99's limit. Not unique.
    """
    discord_user_name: str | None
    """
    The player's Discord username as stored. Mutable, and never the key.
    """
    discord_user_id: str | None
    """
    The player's Discord account id, as a string, or null for a row written before snowflakes were stored. A snowflake exceeds 2^53, so a JSON number loses precision in a browser — Discord's own API sends them as strings for the same reason.
    """
    division: str | None
    """
    The division they are registered in, or null if this event runs on teams.
    """
    division_alt_name: str | None
    """
    The division's short label, or null. Many divisions have none — which is the bug in the view this replaces.
    """
    team: str | None
    """
    The team they are registered in, or null if this event runs on divisions.
    """
    team_alt_name: str | None
    """
    The team's short label, or null.
    """
    registered_at: str
    """
    When the registration that still stands was made, as a UTC instant. A re-join carries the later date.
    """


class Ggp8StatOption(TypedDict):
    id: int
    """
    The option's id, sent back in a `PUT`.
    """
    text: str
    """
    The option's label.
    """


class HealthResponse(TypedDict):
    status: str
    environment: str
    """
    dev, stage or prod.
    """
    version: str
    """
    What the code calls itself.
    """
    release: str
    """
    What was deployed. `unknown` outside a deploy.
    """
    database: str
    """
    The schema this process is configured for. Not proof it is reachable.
    """
    ingame_profile: str | None
    """
    The pengbot99 event profile the in-game rotation was built under, or null for the default rotation.
    """


class HostAssignmentRequest(TypedDict):
    discord_user_id: str
    """
    The host's Discord account id, as a string. A snowflake exceeds 2^53, so a JSON number loses precision in a browser — Discord's own API sends them as strings for the same reason.
    """
    discord_user_name: str
    """
    The host's current Discord username. Mutable, and never the key — it is stored, and used to find a row that carries no snowflake.
    """
    tag: NotRequired[str | None]
    """
    In-game name, used only if this account has no row yet. Ten characters because that is F-Zero 99's limit; a longer one is rejected rather than silently truncated, so the caller decides what to cut.
    """


class LineupTrackResponse(TypedDict):
    name: str
    """
    The track's name, as a client prints it: `mirror Sand Ocean` for a mirror track. A standard track and its classic twin share a name; `type` tells them apart.
    """
    type: str
    """
    `standard`, `mirror`, `classic` or `glitch`.
    """
    short_name: str
    """
    What the lineup's name is spelt from. A mirror track's carries the `m`.
    """


class LiveScoreboardRequest(TypedDict):
    channel_id: str
    """
    The Discord channel the message is in, as a string.
    """
    scheduled_event_id: int
    """
    The `events_scheduled` id the board draws.
    """
    division_id: NotRequired[int | None]
    """
    Narrow the board to this division of the event. Exclusive with `team_id`.
    """
    team_id: NotRequired[int | None]
    """
    Narrow the board to this team of the event. Exclusive with `division_id`.
    """


class LiveScoreboardResponse(TypedDict):
    message_id: str
    """
    The Discord message that is the board, as a string.
    """
    channel_id: str
    """
    The channel the message is in, as a string.
    """
    scheduled_event_id: int
    """
    The `events_scheduled` id the board draws.
    """
    division_id: int | None
    """
    The division the board is narrowed to, or null.
    """
    team_id: int | None
    """
    The team the board is narrowed to, or null.
    """


class LobbyVoteWinnerResponse(TypedDict):
    division_id: int | None
    """
    The `divisions` id of the lobby, or null for the lobby of an event with no divisions.
    """
    track_id: int
    """
    A `tracks` id.
    """
    track_name: str
    """
    The track's name, as a client prints it: `mirror Sand Ocean` for a mirror track. A standard track and its classic twin share a name; `type` tells them apart.
    """
    track_type: str
    """
    `standard`, `mirror`, `classic` or `glitch`.
    """
    track_short_name: str | None
    """
    The track's short name, which says its type: `SO`, `mSO`, `cSO`.
    """


class MachineResponse(TypedDict):
    machine_id: int
    name: str


class MeResponse(TypedDict):
    discord_user_id: str | None
    """
    The person's Discord account id, as a string — a snowflake exceeds 2^53 and a JSON number would lose its low bits. Null for a bot client.
    """
    discord_user_name: NotRequired[str | None]
    """
    The Discord username the session was minted with. Mutable, and never a key.
    """
    client: str | None
    """
    The bot client's name for a key-authenticated caller. Null for a person.
    """
    roles: list[str]
    """
    Discord guild role ids held right now, read live with a short TTL. Strings for the same reason `discord_user_id` is. Always empty for a bot client.
    """
    groups: NotRequired[list[str]]
    """
    Names of the role groups in this deployment's `FZD_API_DISCORD_ROLES` that the caller satisfies — the gates `require_any_role` would open. A client gates its UI on these rather than on role ids, so adding or renaming a staff role is one line of API configuration and no release of the client. A bot client holds every configured group. Absent from the list means refused.
    """


class PlayerEventPointsResponse(TypedDict):
    event: str
    """
    The recurring event, by name. The same value `/v1/events/active` returns as `event`.
    """
    points: int
    """
    Points scored across every counted submission to this event.
    """
    events_played: int
    """
    How many runnings of this event the player scored at. Instances, not submissions.
    """
    scores_counted: int
    """
    How many individual score submissions are behind `points`. Several per running is ordinary.
    """
    first_played_at: str
    """
    Start of the earliest running of this event the player scored at, as a UTC instant.
    """
    last_played_at: str
    """
    Start of the most recent one, as a UTC instant.
    """


class PlayerResultResponse(TypedDict):
    slot_id: int
    """
    The `event_slots` id the result is set on.
    """
    position: int
    """
    Where that slot sits in the event's schedule.
    """
    score: int | None
    """
    The points stored, or null.
    """
    time_cs: int | None
    """
    The time stored, in centiseconds, or null.
    """
    machine_id: int | None
    """
    The machine recorded on the result, or null.
    """
    machine: str | None
    """
    That machine's name, or null.
    """
    modified_dt: str
    """
    When the result was last set, UTC.
    """


class PlayerStatsResponse(TypedDict):
    discord_user_id: str
    """
    The player's Discord account id, as a string. A snowflake exceeds 2^53, so a JSON number loses precision in a browser — Discord's own API sends them as strings for the same reason.
    """
    display_name: str | None
    """
    What to call this player: their in-game tag, or their Discord username if they have never set one. Null when they have neither.
    """
    total_points: int
    """
    Points across every event. The sum of `by_event[].points`.
    """
    events_played: int
    """
    Runnings of any event the player scored at. The sum of `by_event[].events_played`.
    """
    scores_counted: int
    """
    Individual score submissions behind `total_points`.
    """
    first_played_at: str | None
    """
    Start of the earliest event the player scored at, or null if they never have.
    """
    last_played_at: str | None
    """
    Start of the most recent one, or null if they never have.
    """
    by_event: list[PlayerEventPointsResponse]
    """
    One entry per recurring event the player has scored in, most points first, then by name. Empty for a player who has never scored.
    """


class PlayerTagRequest(TypedDict):
    discord_user_name: NotRequired[str | None]
    tag: str


class PlayerTagResponse(TypedDict):
    discord_user_id: str
    tag: str
    display_name: str | None


class RegistrationGroupResponse(TypedDict):
    group_id: int
    """
    A `divisions.id` or `teams.id`. The handle a `PUT` sends to join.
    """
    name: str
    """
    The group's name.
    """
    alt_name: str | None
    """
    A shorter label, or null. Many groups have none.
    """
    emote: str | None
    """
    A Discord emote for the group, or null.
    """
    display_order: int
    """
    The order the guild lists groups in. Rows already arrive in it.
    """
    capacity: int | None
    """
    How many places the group has, or null if uncapped. Null means unlimited, not full.
    """
    registered: int
    """
    How many players currently hold a place in it.
    """


class RegistrationRequest(TypedDict):
    discord_user_name: NotRequired[str | None]
    tag: NotRequired[str | None]
    group_id: int
    """
    A `divisions.id` or `teams.id` belonging to this event.
    """


class RivalGroupResponse(TypedDict):
    name: str
    """
    The group's name.
    """
    alt_name: str | None
    """
    A shorter label, or null.
    """


class RivalPlayerResponse(TypedDict):
    discord_user_id: str
    """
    The player's Discord account id, as a string.
    """
    tag: str | None
    """
    The player's in-game name, or null. Not unique.
    """
    discord_user_name: str | None
    """
    The player's Discord username as stored, or null.
    """


class RivalRequest(TypedDict):
    rival_discord_user_id: str
    """
    The Discord account id of a player registered for the same event, in any division or team.
    """


class RivalResponse(TypedDict):
    player: RivalPlayerResponse
    chosen_at: str
    """
    When this choice was made, as a UTC instant.
    """


class RotationEntryResponse(TypedDict):
    mode: str
    """
    The mode's name.
    """
    mode_short_name: str
    """
    The mode's short name, which is what `?mode=` takes.
    """
    kind: str
    """
    The mode's kind, `prix` or `race`, which is what `?kind=` takes.
    """
    lineup: str | None
    """
    The lineup offered, or null for a mode whose lineup changes within the entry.
    """
    displaced_lineup: str | None
    """
    The league a Secret GP took the place of, and null on every other entry.
    """
    glitch: bool
    """
    Whether the game put glitch content in this entry's place: Secret GP, or a 99 race's glitch track.
    """
    starts_at: str
    ends_at: str


class ScoreResultRequest(TypedDict):
    discord_user_id: str
    """
    The player's Discord account id, as a string. A snowflake exceeds 2^53, so a JSON number loses precision in a browser — Discord's own API sends them as strings for the same reason. A person may submit only for their own account; a bot client may submit for any.
    """
    discord_user_name: str
    """
    The player's current Discord username, used only if this account has no row yet.
    """
    dnf: NotRequired[bool]
    """
    The player raced the slot and has no result for it. Sends a row holding null.
    """
    machine_id: NotRequired[int | None]
    """
    A `machines` id. Required when the event records the machine raced.
    """
    score: NotRequired[int | None]
    """
    Points scored on the slot, zero or more.
    """


class ScoreResultResponse(TypedDict):
    scheduled_event_id: int
    slot_id: int
    """
    The `event_slots` id the result is set on.
    """
    position: int
    """
    Where that slot sits in the event's schedule.
    """
    discord_user_id: str
    """
    Whose result this is, as a string.
    """
    machine_id: int | None
    """
    The machine recorded on the result, or null.
    """
    score: int | None
    """
    The points stored, or null for a submitted no-result.
    """


class ScoreboardFilterResponse(TypedDict):
    division_id: int | None
    team_id: int | None


class ScoringConfigResponse(TypedDict):
    num_mulligans: int
    """
    How many of a player's results drop before totalling.
    """
    max_time_loss_cs: int | None
    """
    The most a time result can lose to the slot's leader, in centiseconds, or null for no cap.
    """


class SlotEntryRequest(TypedDict):
    mode: NotRequired[str | None]
    """
    A mode's short name, e.g. `GP`, `MP`, `99`. Matched without regard to case.
    """
    lineup_id: NotRequired[int | None]
    """
    A `lineups` id, for a slot naming a specific lineup.
    """
    starts_at: NotRequired[str | None]
    """
    When the slot is raced, as a UTC instant, or null if not yet known.
    """
    multiplier: NotRequired[int]
    """
    What a result on this slot is worth before anything else is decided.
    """
    lobby: NotRequired[Literal["public", "private"] | None]
    """
    The kind of lobby the slot is raced in, matched without regard to case. `public` resolves a mode against what the game runs at `starts_at` and is refused where it runs nothing of the kind; `private` refuses a Grand Prix that names no league, and Secret GP. Absent, the kind is not recorded and the slot resolves as it would without one.
    """


class SlotResultResponse(TypedDict):
    slot_id: int | None
    """
    The slot this result is set on, or null for a result that names none.
    """
    score: int | None
    """
    The submitted score, or null: nothing submitted, or a submitted no-result.
    """
    time_cs: int | None
    """
    The submitted time in centiseconds, or null as for `score`.
    """
    value: int | None
    """
    What the result is worth: the score after the slot's multiplier on a points event, the loss to the slot's leader in centiseconds on a time event. Null only on an uncapped time event for a player with no finish on an open slot.
    """
    submitted: bool
    """
    Whether a row exists. A submitted no-result and a missing one are worth the same.
    """
    counted: bool
    """
    False for a result a mulligan dropped; it stays in the list.
    """
    open: bool
    """
    False for a time slot nobody has finished, which is worth 0 to everyone.
    """


class SlotTrackResponse(TypedDict):
    track_id: int
    """
    A `tracks` id, the value a vote on this slot names.
    """
    name: str
    """
    The track's name, as a client prints it: `mirror Sand Ocean` for a mirror track. A standard track and its classic twin share a name; `type` tells them apart.
    """
    type: str
    """
    `standard`, `mirror`, `classic` or `glitch`.
    """
    short_name: str | None
    """
    The track's short name, or null where none is stored.
    """


class TeamTotalResponse(TypedDict):
    group_id: int
    """
    A `teams` id.
    """
    total: int
    rank: int
    """
    Dense rank among the event's teams.
    """


class TimeResultRequest(TypedDict):
    discord_user_id: str
    """
    The player's Discord account id, as a string. A snowflake exceeds 2^53, so a JSON number loses precision in a browser — Discord's own API sends them as strings for the same reason. A person may submit only for their own account; a bot client may submit for any.
    """
    discord_user_name: str
    """
    The player's current Discord username, used only if this account has no row yet.
    """
    dnf: NotRequired[bool]
    """
    The player raced the slot and has no result for it. Sends a row holding null.
    """
    machine_id: NotRequired[int | None]
    """
    A `machines` id. Required when the event records the machine raced.
    """
    time_cs: NotRequired[int | None]
    """
    The time as entered, in centiseconds: 1:30.44 is 9044. Under ten minutes.
    """


class TimeResultResponse(TypedDict):
    scheduled_event_id: int
    slot_id: int
    """
    The `event_slots` id the result is set on.
    """
    position: int
    """
    Where that slot sits in the event's schedule.
    """
    discord_user_id: str
    """
    Whose result this is, as a string.
    """
    machine_id: int | None
    """
    The machine recorded on the result, or null.
    """
    time_cs: int | None
    """
    The time stored, in centiseconds, or null for a submitted no-result.
    """


class TrackResponse(TypedDict):
    track_id: int
    """
    A `tracks` id, the value a vote on a slot names.
    """
    name: str
    """
    The track's name, as a client prints it: `mirror Sand Ocean` for a mirror track. A standard track and its classic twin share a name; `type` tells them apart.
    """
    type: str
    """
    `standard`, `mirror`, `classic` or `glitch`.
    """
    short_name: str | None
    """
    The track's short name, or null where none is stored.
    """


class ValidationError(TypedDict):
    loc: list[str | int]
    msg: str
    type: str
    input: NotRequired[Any]
    ctx: NotRequired[dict[str, Any]]


class VoteRequest(TypedDict):
    track_id: int
    """
    A `tracks` id, one of the slot's `tracks`.
    """
    division_id: NotRequired[int | None]
    """
    The division whose lobby voted. Required on an event with divisions, refused on one without.
    """
    recorded_by_discord_user_id: NotRequired[str | None]
    """
    The Discord account recording the vote, which a bot sends on behalf of the person who ran its command. Absent, it is the signed-in person, and nobody for a bot key.
    """
    recorded_by_discord_user_name: NotRequired[str | None]
    """
    That account's current Discord username.
    """


class VoteWinnerResponse(TypedDict):
    track_id: int
    """
    A `tracks` id.
    """
    track_name: str
    """
    The track's name, as a client prints it.
    """


class YourRegistrationResponse(TypedDict):
    group_id: int
    """
    The `divisions.id` or `teams.id` the caller currently holds.
    """
    registered_at: str | None
    """
    When the standing registration was made, as a UTC instant, or null.
    """


class CatalogueLineupResponse(TypedDict):
    lineup_id: int
    """
    A `lineups` id.
    """
    mode: str
    """
    The mode the lineup belongs to, e.g. `Grand Prix` or `99`.
    """
    mode_short_name: str | None
    """
    The mode's short name, which is what `?mode=` takes, or null where none is stored.
    """
    kind: str
    """
    `prix`, raced in order and scored as one, or `race`, one track voted from a pair.
    """
    name: str | None
    """
    The lineup's name, a key under its mode.
    """
    short_name: str
    """
    The lineup's short name.
    """
    tracks: list[CatalogueTrackResponse]
    """
    The lineup's tracks: in race order on a prix, the pair put to the vote on a race. Never empty.
    """


class ChallengerResponse(TypedDict):
    scheduled_event_id: int
    """
    The event they picked the caller for.
    """
    player: RivalPlayerResponse
    chosen_at: str
    """
    When they made the choice, as a UTC instant.
    """


class Ggp8EvaluationOptions(TypedDict):
    self_evaluation: list[Ggp8StatOption]
    """
    Every "What is your F-Zero 99 experience?" choice.
    """
    most_recent_event: list[Ggp8StatOption]
    """
    Every "most recent major F-ZERO 99 event" choice.
    """


class Ggp8EvaluationResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id.
    """
    self_evaluation: str | None
    """
    The player's "F-Zero 99 experience" answer, or null.
    """
    most_recent_event: str | None
    """
    The player's "most recent major event" answer, or null.
    """
    answered_for_this_event: bool
    """
    Whether the answers are stored against this event rather than carried from the most recent one.
    """
    options: Ggp8EvaluationOptions
    """
    The choices each answer can take.
    """


class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]


class LineupOfferResponse(TypedDict):
    mode: str
    """
    The mode's name.
    """
    mode_short_name: str
    """
    The mode's short name, which is what `?mode=` takes.
    """
    lineup: str
    """
    The lineup's name: a key under its mode, not something to parse. Read `tracks`.
    """
    tracks: list[LineupTrackResponse]
    """
    In race order for a prix; the two put to the vote for a 99 race. Empty for a Grand Prix league, whose tracks this read does not hold.
    """
    starts_at: str
    ends_at: str


class RegistrationEventResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id, the same one `/v1/events/{id}/host` takes.
    """
    event: str
    """
    The recurring event this is an instance of.
    """
    display_name: str | None
    """
    What this instance calls itself, or null.
    """
    description: str | None
    """
    The recurring event's description, or null.
    """
    starts_at: str
    """
    When the event opens, as a UTC instant.
    """
    ends_at: str
    """
    When the event closes, as a UTC instant.
    """
    registration_opens_at: str | None
    """
    When registration opens, as a UTC instant, or null if no window is configured.
    """
    registration_closes_at: str | None
    """
    When registration closes, as a UTC instant, or null if no window is configured.
    """
    registration_open: bool
    """
    Whether registration is open at the request's clock. True when no window is configured.
    """
    mode: str
    """
    `99` or `classic`.
    """
    scoring_method: str
    """
    `points`, `placement` or `time`.
    """
    machine_input_required: bool
    """
    Whether a score submission for this event must name a machine.
    """
    group_kind: str | None
    """
    `division` or `team` — which one this event's groups are — or null if it has none.
    """
    groups: list[RegistrationGroupResponse]
    """
    Every group of this event, in the order the guild lists them.
    """
    your_registration: YourRegistrationResponse | None
    """
    Where the caller is registered, or null if they are not.
    """


class RegistrationsResponse(TypedDict):
    events: list[RegistrationEventResponse]


class RivalCandidateResponse(TypedDict):
    discord_user_id: str
    """
    The player's Discord account id, as a string.
    """
    tag: str | None
    """
    The player's in-game name, or null. Not unique.
    """
    discord_user_name: str | None
    """
    The player's Discord username as stored, or null.
    """
    group: RivalGroupResponse
    """
    The division or team this player is registered in.
    """


class RivalEventResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id, the same one `/v1/events/{id}/host` takes.
    """
    event: str
    """
    The recurring event this is an instance of.
    """
    display_name: str | None
    """
    What this instance calls itself, or null.
    """
    starts_at: str
    """
    When the event starts, as a UTC instant. Picks lock then.
    """
    registered: bool
    """
    Whether the caller is currently registered for this event.
    """
    locked: bool
    """
    Whether the event has started at the request's clock. A locked pick cannot change.
    """
    your_group: RivalGroupResponse | None
    """
    The division or team the caller is registered in, or null if they are not.
    """
    rival: RivalResponse | None
    """
    The caller's pick, or null if they have not made one.
    """
    candidates: list[RivalCandidateResponse]
    """
    Everybody registered for the event the caller may pick, sorted by name. Empty when a pick is not possible.
    """


class RivalsResponse(TypedDict):
    events: list[RivalEventResponse]
    """
    Every event running a Rival Challenge, earliest first. Empty when none is.
    """
    challengers: list[ChallengerResponse]
    """
    Everyone who has picked the caller, by event then by when.
    """


class ScoreboardRowResponse(TypedDict):
    display_name: str | None
    """
    What to print for the player: `tag`, else their Discord username.
    """
    emote: str | None
    """
    The player's emote, an opaque string, or null.
    """
    group_id: int | None
    """
    The player's division or team as `group_kind` says, or null for a player with none.
    """
    results: list[SlotResultResponse]
    """
    One per slot in position order, then any slotless results.
    """
    submissions: int
    """
    How many result rows exist for the player.
    """
    total: int | None
    """
    The sum of counted values; null where a counted value has none.
    """
    rank: int | None
    """
    Dense rank within the board: points descending, time ascending, equal totals sharing a rank. Null for a player with no total.
    """


class SlotResponse(TypedDict):
    slot_id: int
    """
    An `event_slots` id, the handle a result on this slot names.
    """
    position: int
    """
    Where the slot sits in the schedule, unique within the event.
    """
    lineup_id: int
    """
    A `lineups` id.
    """
    lineup_name: str | None
    """
    The lineup's name, or null for a placeholder lineup with its tracks unspecified.
    """
    lineup_short_name: str
    """
    The lineup's short name.
    """
    mode: str
    """
    The mode the lineup belongs to, e.g. `Grand Prix` or `99`. Not the event's own `mode`.
    """
    kind: str
    """
    `prix`, raced in order and scored as one, or `race`, one track voted from a pair.
    """
    max_score: int | None
    """
    The most a score on this slot can be, or null for a mode with no ceiling.
    """
    multiplier: int
    """
    What a result on this slot is worth before anything else is decided.
    """
    starts_at: str | None
    """
    When the slot is raced, as a UTC instant, or null if not entered.
    """
    tracks: list[SlotTrackResponse]
    """
    The lineup's tracks: in race order on a prix slot, the pair put to the vote on a race slot, and empty for a placeholder lineup.
    """
    vote_winner: VoteWinnerResponse | None
    """
    The track voted in on a race slot in the undivided lobby, or null if none is recorded.
    """
    vote_winners: list[LobbyVoteWinnerResponse]
    """
    The track voted in per lobby, one entry for each lobby with a vote recorded. An event with divisions has one lobby per division, and two divisions can hold different winners on one slot.
    """
    lobby: str | None
    """
    The kind of lobby the slot is raced in: `public`, joining what the game runs at that minute, or `private`, a room the host opens. Null where the slot does not say, which is not public.
    """


class EventDetailResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id.
    """
    event: str
    """
    The recurring event this is an instance of, e.g. `friday_eu`.
    """
    display_name: str | None
    """
    What this instance calls itself, or null — most instances have none and `event` is the fallback.
    """
    starts_at: str
    """
    When the event opens, as a UTC instant.
    """
    ends_at: str
    """
    When the event closes, as a UTC instant. Exclusive: an event is no longer active at this instant.
    """
    mode: str
    """
    `99` or `classic`.
    """
    scoring_method: str
    """
    `points`, `placement` or `time`.
    """
    machine_input_required: bool
    """
    Whether a score submission for this event must name a machine.
    """
    group_kind: str | None
    """
    `division` or `team` for a grouped event, or null for an event with neither.
    """
    groups: list[EventGroupResponse]
    """
    The event's divisions or teams, as `group_kind` says, in display order. Empty when null.
    """
    slots: list[SlotResponse]
    """
    The schedule, in position order; the same list `/schedule` answers.
    """
    scoring: ScoringConfigResponse


class ScoreboardResponse(TypedDict):
    scheduled_event_id: int
    """
    An `events_scheduled` id.
    """
    group_kind: str | None
    """
    `division`, `team` or null, as `/v1/events/{id}` says.
    """
    scoring_method: str
    """
    `points` or `time`.
    """
    filter: ScoreboardFilterResponse
    num_mulligans: int
    """
    How many results per player are dropped.
    """
    max_time_loss_cs: int | None
    """
    The most a time result loses to its slot's leader, in centiseconds, or null for no cap.
    """
    rows: list[ScoreboardRowResponse]
    team_totals: list[TeamTotalResponse]
    """
    Empty unless `group_kind` is `team`.
    """
