"""Regenerate `src/fzdbot/api_types.py` from the API's OpenAPI document.

    uv run scripts/api_types.py                # from the ../fzd-api checkout
    uv run scripts/api_types.py --url URL      # from a running API's /openapi.json

The checkout is the default because a deployed API can be behind the branch
being worked against, and because the running app's document carries the
schemas' field descriptions, which become the attribute docstrings. Every
response schema becomes one `TypedDict` under its own name with its wire
field names; nothing is filtered or renamed.
"""

import argparse
import json
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "src" / "fzdbot" / "api_types.py"
API_CHECKOUT = REPO.parent / "fzd-api"

DUMP_OPENAPI = "import json; from fzd_api.main import create_app; print(json.dumps(create_app().openapi()))"


def document_from_checkout(checkout: Path) -> tuple[str, str]:
    """The document, and the commit it describes; a dirty tree is marked."""
    document = subprocess.run(
        ["uv", "run", "--quiet", "python", "-c", DUMP_OPENAPI],
        cwd=checkout,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    commit = subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"], cwd=checkout, check=True, capture_output=True, text=True
    ).stdout.strip()
    dirty = subprocess.run(["git", "status", "--porcelain"], cwd=checkout, check=True, capture_output=True, text=True)
    if dirty.stdout.strip():
        commit += " (with uncommitted changes)"
    return document, f"fzd-api {commit}"


def document_from_url(url: str) -> tuple[str, str]:
    with urllib.request.urlopen(url, timeout=10) as response:
        return response.read().decode(), url


def generate(document: str, source: str) -> str:
    with tempfile.TemporaryDirectory() as scratch:
        spec = Path(scratch) / "openapi.json"
        spec.write_text(document)
        out = Path(scratch) / "api_types.py"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "datamodel_code_generator",
                "--input",
                str(spec),
                "--input-file-type",
                "openapi",
                "--output",
                str(out),
                "--output-model-type",
                "typing.TypedDict",
                "--target-python-version",
                "3.12",
                "--use-field-description",
                "--disable-timestamp",
                "--formatters",
                "ruff-format",
            ],
            check=True,
        )
        generated = out.read_text()
    body = generated.split("\n", 3)[3] if generated.startswith("# generated by") else generated
    header = (
        f'"""The FZD API\'s response and request shapes, as `TypedDict`s.\n'
        f"\n"
        f"GENERATED by `uv run scripts/api_types.py`; do not edit.\n"
        f"Source: {source}.\n"
        f"Each class is one schema of the API's OpenAPI document under its own name\n"
        f"and wire field names, with the schema's field descriptions as attribute\n"
        f"docstrings. Instants are ISO 8601 strings. A `TypedDict` is a claim the type\n"
        f"checker verifies at every read site, not a parser: nothing validates a\n"
        f"response against it.\n"
        f'"""\n\n'
    )
    return header + body


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--url", help="read /openapi.json from a running API instead of the checkout")
    parser.add_argument(
        "--checkout", type=Path, default=API_CHECKOUT, help=f"the fzd-api checkout (default {API_CHECKOUT})"
    )
    args = parser.parse_args()
    document, source = document_from_url(args.url) if args.url else document_from_checkout(args.checkout)
    version = json.loads(document)["info"]["version"]
    OUTPUT.write_text(generate(document, f"{source}, API version {version}"))
    subprocess.run(["uv", "run", "--quiet", "ruff", "check", "--fix", "--quiet", str(OUTPUT)], cwd=REPO, check=True)
    subprocess.run(["uv", "run", "--quiet", "ruff", "format", "--quiet", str(OUTPUT)], cwd=REPO, check=True)
    print(f"wrote {OUTPUT.relative_to(REPO)} from {source}")


if __name__ == "__main__":
    main()
